### ISSUE TITLE
Question: SSDT for USB Asmedi

### ISSUE THREAD

**Issue by zikphil** [korzhyk/CLOVER-Z370-AORUS-Gaming-7#11]
Hi!

I was browsing your code base and was wondering what were the benefits of using an SSDT vs only a DSDT. We have the same setup and with specific USB devices I am having issues where sometimes the system panics out and reboot, if I unplug my USB Capture Card it never happens. Which leads me to believe something is wrong with USB ports Power, is it something an SSDT would fix?

Thanks and great work on this repo.

**Comment by korzhyk** [comment]
DSDT vs DSDT+SSDT: my opinion is second variant, so this is easy to tweak HW without touching main table.

I using this config for a nine months and there a no any panics related to USB, I got one panic a month ago, but it's related to my GPU.

USB power currents described in `Device (USBX)` in ext SSDT.

In your case I can't help you because there no any logs provided, sorry.
